// Code generated by "stringer -type=Direction"; DO NOT EDIT.

package model

import "strconv"

const _Direction_name = "NorthNorthEastEastSouthEastSouthSouthWestWestNorthWest"

var _Direction_index = [...]uint8{0, 5, 14, 18, 27, 32, 41, 45, 54}

func (i Direction) String() string {
	if i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
