// Code generated by protoc-gen-go. DO NOT EDIT.
// source: characterservice.proto

/*
Package services is a generated protocol buffer package.

It is generated from these files:
	characterservice.proto

It has these top-level messages:
	CommandMessage
	EventMessage
	SayCommand
	CharacterDescription
	RoomDescriptionEvent
	CharacterWakesUpEvent
	CharacterSleepsEvent
	CharacterSpeaksEvent
*/
package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommandType int32

const (
	CommandType_CmdLook CommandType = 0
	CommandType_CmdSay  CommandType = 1
)

var CommandType_name = map[int32]string{
	0: "CmdLook",
	1: "CmdSay",
}
var CommandType_value = map[string]int32{
	"CmdLook": 0,
	"CmdSay":  1,
}

func (x CommandType) String() string {
	return proto.EnumName(CommandType_name, int32(x))
}
func (CommandType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EventType int32

const (
	EventType_EvtRoomDescription  EventType = 0
	EventType_EvtCharacterWakesUp EventType = 1
	EventType_EvtCharacterSleeps  EventType = 2
	EventType_EvtCharacterSpeaks  EventType = 3
)

var EventType_name = map[int32]string{
	0: "EvtRoomDescription",
	1: "EvtCharacterWakesUp",
	2: "EvtCharacterSleeps",
	3: "EvtCharacterSpeaks",
}
var EventType_value = map[string]int32{
	"EvtRoomDescription":  0,
	"EvtCharacterWakesUp": 1,
	"EvtCharacterSleeps":  2,
	"EvtCharacterSpeaks":  3,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}
func (EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CommandMessage struct {
	Type    CommandType `protobuf:"varint,1,opt,name=type,enum=services.CommandType" json:"type,omitempty"`
	Payload []byte      `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *CommandMessage) Reset()                    { *m = CommandMessage{} }
func (m *CommandMessage) String() string            { return proto.CompactTextString(m) }
func (*CommandMessage) ProtoMessage()               {}
func (*CommandMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommandMessage) GetType() CommandType {
	if m != nil {
		return m.Type
	}
	return CommandType_CmdLook
}

func (m *CommandMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type EventMessage struct {
	Type    EventType `protobuf:"varint,1,opt,name=type,enum=services.EventType" json:"type,omitempty"`
	Payload []byte    `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *EventMessage) Reset()                    { *m = EventMessage{} }
func (m *EventMessage) String() string            { return proto.CompactTextString(m) }
func (*EventMessage) ProtoMessage()               {}
func (*EventMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EventMessage) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_EvtRoomDescription
}

func (m *EventMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Commands
type SayCommand struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
}

func (m *SayCommand) Reset()                    { *m = SayCommand{} }
func (m *SayCommand) String() string            { return proto.CompactTextString(m) }
func (*SayCommand) ProtoMessage()               {}
func (*SayCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SayCommand) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// Events
type CharacterDescription struct {
	Id    int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Awake bool   `protobuf:"varint,3,opt,name=awake" json:"awake,omitempty"`
}

func (m *CharacterDescription) Reset()                    { *m = CharacterDescription{} }
func (m *CharacterDescription) String() string            { return proto.CompactTextString(m) }
func (*CharacterDescription) ProtoMessage()               {}
func (*CharacterDescription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CharacterDescription) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CharacterDescription) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CharacterDescription) GetAwake() bool {
	if m != nil {
		return m.Awake
	}
	return false
}

type RoomDescriptionEvent struct {
	Name        string                  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string                  `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Characters  []*CharacterDescription `protobuf:"bytes,3,rep,name=characters" json:"characters,omitempty"`
}

func (m *RoomDescriptionEvent) Reset()                    { *m = RoomDescriptionEvent{} }
func (m *RoomDescriptionEvent) String() string            { return proto.CompactTextString(m) }
func (*RoomDescriptionEvent) ProtoMessage()               {}
func (*RoomDescriptionEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RoomDescriptionEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoomDescriptionEvent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RoomDescriptionEvent) GetCharacters() []*CharacterDescription {
	if m != nil {
		return m.Characters
	}
	return nil
}

type CharacterWakesUpEvent struct {
	Character *CharacterDescription `protobuf:"bytes,1,opt,name=character" json:"character,omitempty"`
}

func (m *CharacterWakesUpEvent) Reset()                    { *m = CharacterWakesUpEvent{} }
func (m *CharacterWakesUpEvent) String() string            { return proto.CompactTextString(m) }
func (*CharacterWakesUpEvent) ProtoMessage()               {}
func (*CharacterWakesUpEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CharacterWakesUpEvent) GetCharacter() *CharacterDescription {
	if m != nil {
		return m.Character
	}
	return nil
}

type CharacterSleepsEvent struct {
	Character *CharacterDescription `protobuf:"bytes,1,opt,name=character" json:"character,omitempty"`
}

func (m *CharacterSleepsEvent) Reset()                    { *m = CharacterSleepsEvent{} }
func (m *CharacterSleepsEvent) String() string            { return proto.CompactTextString(m) }
func (*CharacterSleepsEvent) ProtoMessage()               {}
func (*CharacterSleepsEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CharacterSleepsEvent) GetCharacter() *CharacterDescription {
	if m != nil {
		return m.Character
	}
	return nil
}

type CharacterSpeaksEvent struct {
	Character *CharacterDescription `protobuf:"bytes,1,opt,name=character" json:"character,omitempty"`
	Content   string                `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *CharacterSpeaksEvent) Reset()                    { *m = CharacterSpeaksEvent{} }
func (m *CharacterSpeaksEvent) String() string            { return proto.CompactTextString(m) }
func (*CharacterSpeaksEvent) ProtoMessage()               {}
func (*CharacterSpeaksEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CharacterSpeaksEvent) GetCharacter() *CharacterDescription {
	if m != nil {
		return m.Character
	}
	return nil
}

func (m *CharacterSpeaksEvent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*CommandMessage)(nil), "services.CommandMessage")
	proto.RegisterType((*EventMessage)(nil), "services.EventMessage")
	proto.RegisterType((*SayCommand)(nil), "services.SayCommand")
	proto.RegisterType((*CharacterDescription)(nil), "services.CharacterDescription")
	proto.RegisterType((*RoomDescriptionEvent)(nil), "services.RoomDescriptionEvent")
	proto.RegisterType((*CharacterWakesUpEvent)(nil), "services.CharacterWakesUpEvent")
	proto.RegisterType((*CharacterSleepsEvent)(nil), "services.CharacterSleepsEvent")
	proto.RegisterType((*CharacterSpeaksEvent)(nil), "services.CharacterSpeaksEvent")
	proto.RegisterEnum("services.CommandType", CommandType_name, CommandType_value)
	proto.RegisterEnum("services.EventType", EventType_name, EventType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Character service

type CharacterClient interface {
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (Character_SubscribeClient, error)
}

type characterClient struct {
	cc *grpc.ClientConn
}

func NewCharacterClient(cc *grpc.ClientConn) CharacterClient {
	return &characterClient{cc}
}

func (c *characterClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (Character_SubscribeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Character_serviceDesc.Streams[0], c.cc, "/services.Character/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &characterSubscribeClient{stream}
	return x, nil
}

type Character_SubscribeClient interface {
	Send(*CommandMessage) error
	Recv() (*EventMessage, error)
	grpc.ClientStream
}

type characterSubscribeClient struct {
	grpc.ClientStream
}

func (x *characterSubscribeClient) Send(m *CommandMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *characterSubscribeClient) Recv() (*EventMessage, error) {
	m := new(EventMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Character service

type CharacterServer interface {
	Subscribe(Character_SubscribeServer) error
}

func RegisterCharacterServer(s *grpc.Server, srv CharacterServer) {
	s.RegisterService(&_Character_serviceDesc, srv)
}

func _Character_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CharacterServer).Subscribe(&characterSubscribeServer{stream})
}

type Character_SubscribeServer interface {
	Send(*EventMessage) error
	Recv() (*CommandMessage, error)
	grpc.ServerStream
}

type characterSubscribeServer struct {
	grpc.ServerStream
}

func (x *characterSubscribeServer) Send(m *EventMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *characterSubscribeServer) Recv() (*CommandMessage, error) {
	m := new(CommandMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Character_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.Character",
	HandlerType: (*CharacterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Character_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "characterservice.proto",
}

func init() { proto.RegisterFile("characterservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0xd7, 0x49, 0x69, 0x9b, 0x49, 0xb5, 0x8a, 0xdc, 0xed, 0x12, 0x71, 0x40, 0x51, 0x0e,
	0x25, 0xf4, 0xb0, 0x42, 0xcb, 0x15, 0x71, 0x09, 0x7b, 0x03, 0xa9, 0x38, 0x5d, 0x71, 0xf6, 0x26,
	0x23, 0x88, 0xb2, 0x89, 0xad, 0xc4, 0x04, 0xe5, 0x1d, 0x78, 0x68, 0x54, 0x37, 0x7f, 0xdc, 0x14,
	0x09, 0x0e, 0xbd, 0x79, 0x46, 0xdf, 0xfc, 0xfc, 0x79, 0xc6, 0x03, 0xeb, 0xf4, 0x07, 0xaf, 0x79,
	0xaa, 0xb0, 0x6e, 0xb0, 0x6e, 0xf3, 0x14, 0x37, 0xb2, 0x16, 0x4a, 0xd0, 0xf3, 0x3e, 0x6c, 0xc2,
	0x3d, 0x2c, 0x63, 0x51, 0x96, 0xbc, 0xca, 0xbe, 0x60, 0xd3, 0xf0, 0xef, 0x48, 0xdf, 0xc2, 0x89,
	0xea, 0x24, 0xfa, 0x24, 0x20, 0xd1, 0x72, 0x7b, 0xb5, 0x19, 0xa4, 0x9b, 0x5e, 0x77, 0xd7, 0x49,
	0x64, 0x5a, 0x42, 0x7d, 0x38, 0x93, 0xbc, 0x3b, 0x0a, 0x9e, 0xf9, 0x56, 0x40, 0xa2, 0x0b, 0x36,
	0x84, 0xe1, 0x57, 0xb8, 0xd8, 0xb5, 0x58, 0xa9, 0x01, 0xfa, 0xe6, 0x11, 0xf4, 0x72, 0x82, 0x6a,
	0xd5, 0x7f, 0x21, 0xaf, 0x01, 0x12, 0xde, 0xf5, 0x26, 0xee, 0x75, 0xa9, 0xa8, 0x14, 0x56, 0x4a,
	0x33, 0x1d, 0x36, 0x84, 0xe1, 0x2d, 0xac, 0xe2, 0xe1, 0xd5, 0x9f, 0xb0, 0x49, 0xeb, 0x5c, 0xaa,
	0x5c, 0x54, 0x74, 0x09, 0x56, 0x9e, 0x69, 0xb1, 0xcd, 0xac, 0x3c, 0xa3, 0x14, 0x4e, 0x2a, 0x5e,
	0xa2, 0xbe, 0xc6, 0x61, 0xfa, 0x4c, 0x57, 0xf0, 0x82, 0xff, 0xe2, 0x05, 0xfa, 0x76, 0x40, 0xa2,
	0x73, 0xf6, 0x10, 0x84, 0xbf, 0x09, 0xac, 0x98, 0x10, 0xa5, 0x41, 0xd3, 0xb6, 0x47, 0x04, 0x31,
	0x10, 0x01, 0xb8, 0xd9, 0xa4, 0xeb, 0xe9, 0x66, 0x8a, 0x7e, 0x04, 0x98, 0xc6, 0xe2, 0xdb, 0x81,
	0x1d, 0xb9, 0xdb, 0xd7, 0x46, 0x9b, 0xff, 0x62, 0x9e, 0x19, 0x15, 0xe1, 0x1e, 0xae, 0x46, 0xcd,
	0x37, 0x5e, 0x60, 0xb3, 0x97, 0x0f, 0x76, 0x3e, 0x80, 0x33, 0xca, 0xb4, 0xa7, 0x7f, 0x73, 0xa7,
	0x82, 0xf0, 0xce, 0xe8, 0x5b, 0x72, 0x44, 0x94, 0xcd, 0x73, 0x50, 0x2b, 0x93, 0x2a, 0x91, 0x17,
	0xcf, 0x41, 0x35, 0xa7, 0x6f, 0x3d, 0x9a, 0xfe, 0xcd, 0x35, 0xb8, 0xc6, 0x3f, 0xa5, 0x2e, 0x9c,
	0xc5, 0x65, 0xf6, 0x59, 0x88, 0xc2, 0x5b, 0x50, 0x80, 0xd3, 0xb8, 0xcc, 0x12, 0xde, 0x79, 0xe4,
	0xe6, 0x08, 0xce, 0xf8, 0xf5, 0xe8, 0x1a, 0xe8, 0xae, 0x55, 0xb3, 0x11, 0x7b, 0x0b, 0xfa, 0x12,
	0x2e, 0x77, 0xad, 0x9a, 0x37, 0xdb, 0x23, 0x7d, 0xc1, 0xac, 0x5d, 0x9e, 0xf5, 0x24, 0xaf, 0x1f,
	0xec, 0xd9, 0xdb, 0x5b, 0x70, 0xc6, 0x24, 0x8d, 0xc1, 0x49, 0x7e, 0x1e, 0xee, 0xef, 0x39, 0x20,
	0xf5, 0x9f, 0xec, 0x57, 0xbf, 0x32, 0xaf, 0xd6, 0xb3, 0x25, 0xe9, 0xf3, 0xe1, 0x22, 0x22, 0xef,
	0xc8, 0xe1, 0x54, 0x2f, 0xf2, 0xfb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x36, 0x81, 0xb9,
	0xe2, 0x03, 0x00, 0x00,
}
