// Code generated by protoc-gen-go. DO NOT EDIT.
// source: characterservice.proto

/*
Package services is a generated protocol buffer package.

It is generated from these files:
	characterservice.proto

It has these top-level messages:
	CommandMessage
	EventMessage
	CharacterDescription
	RoomDescriptionEvent
	CharacterWakesUpEvent
	CharacterSleepsEvent
*/
package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommandType int32

const (
	CommandType_CmdLook CommandType = 0
)

var CommandType_name = map[int32]string{
	0: "CmdLook",
}
var CommandType_value = map[string]int32{
	"CmdLook": 0,
}

func (x CommandType) String() string {
	return proto.EnumName(CommandType_name, int32(x))
}
func (CommandType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EventType int32

const (
	EventType_EvtRoomDescription  EventType = 0
	EventType_EvtCharacterWakesUp EventType = 1
	EventType_EvtCharacterSleeps  EventType = 2
)

var EventType_name = map[int32]string{
	0: "EvtRoomDescription",
	1: "EvtCharacterWakesUp",
	2: "EvtCharacterSleeps",
}
var EventType_value = map[string]int32{
	"EvtRoomDescription":  0,
	"EvtCharacterWakesUp": 1,
	"EvtCharacterSleeps":  2,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}
func (EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CommandMessage struct {
	Type    CommandType `protobuf:"varint,1,opt,name=type,enum=services.CommandType" json:"type,omitempty"`
	Payload []byte      `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *CommandMessage) Reset()                    { *m = CommandMessage{} }
func (m *CommandMessage) String() string            { return proto.CompactTextString(m) }
func (*CommandMessage) ProtoMessage()               {}
func (*CommandMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommandMessage) GetType() CommandType {
	if m != nil {
		return m.Type
	}
	return CommandType_CmdLook
}

func (m *CommandMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type EventMessage struct {
	Type    EventType `protobuf:"varint,1,opt,name=type,enum=services.EventType" json:"type,omitempty"`
	Payload []byte    `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *EventMessage) Reset()                    { *m = EventMessage{} }
func (m *EventMessage) String() string            { return proto.CompactTextString(m) }
func (*EventMessage) ProtoMessage()               {}
func (*EventMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EventMessage) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_EvtRoomDescription
}

func (m *EventMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Events
type CharacterDescription struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Awake bool   `protobuf:"varint,2,opt,name=awake" json:"awake,omitempty"`
}

func (m *CharacterDescription) Reset()                    { *m = CharacterDescription{} }
func (m *CharacterDescription) String() string            { return proto.CompactTextString(m) }
func (*CharacterDescription) ProtoMessage()               {}
func (*CharacterDescription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CharacterDescription) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CharacterDescription) GetAwake() bool {
	if m != nil {
		return m.Awake
	}
	return false
}

type RoomDescriptionEvent struct {
	Name        string                  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string                  `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Characters  []*CharacterDescription `protobuf:"bytes,3,rep,name=characters" json:"characters,omitempty"`
}

func (m *RoomDescriptionEvent) Reset()                    { *m = RoomDescriptionEvent{} }
func (m *RoomDescriptionEvent) String() string            { return proto.CompactTextString(m) }
func (*RoomDescriptionEvent) ProtoMessage()               {}
func (*RoomDescriptionEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RoomDescriptionEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoomDescriptionEvent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RoomDescriptionEvent) GetCharacters() []*CharacterDescription {
	if m != nil {
		return m.Characters
	}
	return nil
}

type CharacterWakesUpEvent struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CharacterWakesUpEvent) Reset()                    { *m = CharacterWakesUpEvent{} }
func (m *CharacterWakesUpEvent) String() string            { return proto.CompactTextString(m) }
func (*CharacterWakesUpEvent) ProtoMessage()               {}
func (*CharacterWakesUpEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CharacterWakesUpEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CharacterSleepsEvent struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CharacterSleepsEvent) Reset()                    { *m = CharacterSleepsEvent{} }
func (m *CharacterSleepsEvent) String() string            { return proto.CompactTextString(m) }
func (*CharacterSleepsEvent) ProtoMessage()               {}
func (*CharacterSleepsEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CharacterSleepsEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*CommandMessage)(nil), "services.CommandMessage")
	proto.RegisterType((*EventMessage)(nil), "services.EventMessage")
	proto.RegisterType((*CharacterDescription)(nil), "services.CharacterDescription")
	proto.RegisterType((*RoomDescriptionEvent)(nil), "services.RoomDescriptionEvent")
	proto.RegisterType((*CharacterWakesUpEvent)(nil), "services.CharacterWakesUpEvent")
	proto.RegisterType((*CharacterSleepsEvent)(nil), "services.CharacterSleepsEvent")
	proto.RegisterEnum("services.CommandType", CommandType_name, CommandType_value)
	proto.RegisterEnum("services.EventType", EventType_name, EventType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Character service

type CharacterClient interface {
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (Character_SubscribeClient, error)
}

type characterClient struct {
	cc *grpc.ClientConn
}

func NewCharacterClient(cc *grpc.ClientConn) CharacterClient {
	return &characterClient{cc}
}

func (c *characterClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (Character_SubscribeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Character_serviceDesc.Streams[0], c.cc, "/services.Character/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &characterSubscribeClient{stream}
	return x, nil
}

type Character_SubscribeClient interface {
	Send(*CommandMessage) error
	Recv() (*EventMessage, error)
	grpc.ClientStream
}

type characterSubscribeClient struct {
	grpc.ClientStream
}

func (x *characterSubscribeClient) Send(m *CommandMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *characterSubscribeClient) Recv() (*EventMessage, error) {
	m := new(EventMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Character service

type CharacterServer interface {
	Subscribe(Character_SubscribeServer) error
}

func RegisterCharacterServer(s *grpc.Server, srv CharacterServer) {
	s.RegisterService(&_Character_serviceDesc, srv)
}

func _Character_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CharacterServer).Subscribe(&characterSubscribeServer{stream})
}

type Character_SubscribeServer interface {
	Send(*EventMessage) error
	Recv() (*CommandMessage, error)
	grpc.ServerStream
}

type characterSubscribeServer struct {
	grpc.ServerStream
}

func (x *characterSubscribeServer) Send(m *EventMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *characterSubscribeServer) Recv() (*CommandMessage, error) {
	m := new(CommandMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Character_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.Character",
	HandlerType: (*CharacterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Character_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "characterservice.proto",
}

func init() { proto.RegisterFile("characterservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x5f, 0x6b, 0xea, 0x40,
	0x10, 0xc5, 0x8d, 0x7a, 0xaf, 0x66, 0x22, 0x12, 0xd6, 0x3f, 0x37, 0xf8, 0x70, 0x09, 0x79, 0xb9,
	0xb9, 0x16, 0xa4, 0xd8, 0xf7, 0x52, 0x48, 0x7d, 0x6b, 0xa1, 0x5d, 0x95, 0x3e, 0xaf, 0xc9, 0xd0,
	0x8a, 0x26, 0xbb, 0x64, 0xb7, 0x29, 0x7e, 0x87, 0x7e, 0xe8, 0xd2, 0x35, 0xd1, 0x34, 0x55, 0xe8,
	0x5b, 0x66, 0x38, 0xf3, 0xcb, 0xcc, 0xd9, 0x03, 0xc3, 0xf0, 0x85, 0xa5, 0x2c, 0x54, 0x98, 0x4a,
	0x4c, 0xb3, 0x75, 0x88, 0x13, 0x91, 0x72, 0xc5, 0x49, 0x3b, 0x2f, 0xa5, 0xb7, 0x84, 0x6e, 0xc0,
	0xe3, 0x98, 0x25, 0xd1, 0x3d, 0x4a, 0xc9, 0x9e, 0x91, 0xfc, 0x87, 0xa6, 0xda, 0x09, 0x74, 0x0c,
	0xd7, 0xf0, 0xbb, 0xd3, 0xc1, 0xa4, 0x90, 0x4e, 0x72, 0xdd, 0x62, 0x27, 0x90, 0x6a, 0x09, 0x71,
	0xa0, 0x25, 0xd8, 0x6e, 0xcb, 0x59, 0xe4, 0xd4, 0x5d, 0xc3, 0xef, 0xd0, 0xa2, 0xf4, 0x1e, 0xa1,
	0x33, 0xcb, 0x30, 0x51, 0x05, 0xf4, 0xdf, 0x17, 0x68, 0xef, 0x08, 0xd5, 0xaa, 0x1f, 0x21, 0x6f,
	0xa0, 0x1f, 0x14, 0xd7, 0xdc, 0xa2, 0x0c, 0xd3, 0xb5, 0x50, 0x6b, 0x9e, 0x10, 0x02, 0xcd, 0x84,
	0xc5, 0x7b, 0xb4, 0x49, 0xf5, 0x37, 0xe9, 0xc3, 0x2f, 0xf6, 0xc6, 0x36, 0xa8, 0x19, 0x6d, 0xba,
	0x2f, 0xbc, 0x77, 0x03, 0xfa, 0x94, 0xf3, 0xb8, 0x34, 0xad, 0x7f, 0x7f, 0x12, 0xe1, 0x82, 0x15,
	0x1d, 0x75, 0x1a, 0x64, 0xd2, 0x72, 0x8b, 0x5c, 0x03, 0x1c, 0xed, 0x75, 0x1a, 0x6e, 0xc3, 0xb7,
	0xa6, 0x7f, 0x4b, 0x76, 0x9d, 0x58, 0x96, 0x96, 0x26, 0xbc, 0x0b, 0x18, 0x1c, 0x34, 0x4f, 0x6c,
	0x83, 0x72, 0x29, 0xce, 0xae, 0xe3, 0x8d, 0x4b, 0xd7, 0xcf, 0xb7, 0x88, 0x42, 0x9e, 0xd5, 0x8e,
	0x47, 0x60, 0x95, 0xde, 0x8a, 0x58, 0xd0, 0x0a, 0xe2, 0xe8, 0x8e, 0xf3, 0x8d, 0x5d, 0x1b, 0x2f,
	0xc0, 0x3c, 0x58, 0x4e, 0x86, 0x40, 0x66, 0x99, 0xaa, 0x58, 0x62, 0xd7, 0xc8, 0x1f, 0xe8, 0xcd,
	0x32, 0x55, 0x5d, 0xce, 0x36, 0xf2, 0x81, 0xca, 0x22, 0x76, 0x7d, 0xfa, 0x00, 0xe6, 0xa1, 0x49,
	0x02, 0x30, 0xe7, 0xaf, 0xab, 0x4f, 0xde, 0x0a, 0x89, 0xf3, 0x2d, 0x3f, 0x79, 0x24, 0x46, 0xc3,
	0x4a, 0x08, 0xf2, 0xbe, 0x57, 0xf3, 0x8d, 0x4b, 0x63, 0xf5, 0x5b, 0x07, 0xf5, 0xea, 0x23, 0x00,
	0x00, 0xff, 0xff, 0xd7, 0xa2, 0xcf, 0x0c, 0xc2, 0x02, 0x00, 0x00,
}
